[package]
name = "cml-chain-wasm"
version = "6.0.0"
edition = "2018"
authors = ["dcSpark"]
license = "MIT"
description = "Multiplatform WASM SDK for main Cardano blockchain functionality"
documentation = "https://github.com/dcSpark/cardano-multiplatform-lib/docs"
repository = "https://github.com/dcSpark/cardano-multiplatform-lib"
readme = "../../README.md"
keywords = ["cardano"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cml-chain = { path = "../rust", version = "6.0.0", features = ["used_from_wasm"] }
cml-core = { path = "../../core/rust", version = "6.0.0" }
cml-core-wasm = { path = "../../core/wasm", version = "6.0.0" }
# TODO: remove this dependency if possible to reduce confusion? maybe pub export necessary things in crypto-wasm?
cml-crypto = { path = "../../crypto/rust", version = "6.0.0" }
cml-crypto-wasm = { path = "../../crypto/wasm", version = "6.0.0" }
cbor_event = "2.4.0"
hex = "0.4.0"
wasm-bindgen = { version = "0.2.87" }
linked-hash-map = "0.5.3"
serde_json = "1.0.57"
serde-wasm-bindgen = "0.4.5"
